improved accessibility
UCLComputerScience/COMP0016_2020_21_Team20 pull request #139
Opened 2021-03-13 11:43 UTC by mateuszz7

before:
![image](https://user-images.githubusercontent.com/55792866/111028834-3ab17f00-83f1-11eb-8fba-c97c0cb6f876.png)

after:
![image](https://user-images.githubusercontent.com/55792866/111028844-47ce6e00-83f1-11eb-952f-ef387e81b454.png)

closes #126

2021-03-13 12:12 UTC, shu8 requested changes
looks good and much better accessibility scores!

I think we just need to change the phrasing of the labels and we're good to merge!

2021-03-13 12:12 UTC, shu8 commented on components/AnalyticsAccordion/AnalyticsAccordion.js
> +      aria-label="analyticsAccordion"
I think Aria Labels (and form `labels` too) are supposed to be short, 'human readable' (/audible) phrases -- the idea is that screen readers will read out this text to describe what is being shown

so this should be something like "Personal analytics" or something I think

2021-03-13 12:12 UTC, shu8 commented on components/CirclesAccordion/CirclesAccordion.js
> +      aria-label="quickSummary"
"Quick summary" etc.

2021-03-13 12:12 UTC, shu8 commented on components/DepartmentsTable/DepartmentsTable.js
> +            <Icon aria-label={'copy' + i} id={'copy' + i} icon="clone" />
this can just be "Copy to clipboard" for all of them (doesn't need to be different for each one AFAIK)

2021-03-13 12:12 UTC, shu8 commented on components/Filters/Filters.js
> +        aria-label="mentoring"
"Mentoring session filter"

2021-03-13 12:12 UTC, shu8 commented on components/Filters/Filters.js
> +        aria-label="visualisation"
"Visualisation type filter"

2021-03-13 12:12 UTC, shu8 commented on components/Header/Header.js
> -
i think we can keep these!

2021-03-13 12:12 UTC, shu8 commented on components/Info/Info.js
> +      <text className={styles.hidden}>{props.url}</text>
does `aria-label` on the `a` not work for this?

2021-03-13 12:14 UTC, mateuszz7 commented on components/Info/Info.js
> +      <text className={styles.hidden}>{props.url}</text>
nope, i looked it up an apparently needs actual text

2021-03-13 12:15 UTC, mateuszz7 commented on components/Header/Header.js
> -
oh idk why that got deleted will change

2021-03-14 14:04 UTC, shu8 requested changes
just a few more!

2021-03-14 14:04 UTC, shu8 commented on components/QuestionsTable/QuestionsTable.js
> +            id={'saveEdit' + i}
"Save"

2021-03-14 14:04 UTC, shu8 commented on components/QuestionsTable/QuestionsTable.js
> +            aria-label={'cancelEdit' + i}
"Cancel"

2021-03-14 14:04 UTC, shu8 commented on components/QuestionsTable/QuestionsTable.js
> +            aria-label={'edit' + i}
"Edit Question"

2021-03-14 14:04 UTC, shu8 commented on components/UrlsTable/UrlsTable.js
> +            aria-label={'saveEdit' + i}
"Save"

2021-03-14 14:04 UTC, shu8 commented on components/UrlsTable/UrlsTable.js
> +            aria-label={'cancelEdit' + i}
"Cancel"

2021-03-14 14:04 UTC, shu8 commented on components/UrlsTable/UrlsTable.js
> +            aria-label={'edit' + i}
"Edit URL"

2021-03-14 14:04 UTC, shu8 commented on components/WordsQuestion/WordsQuestion.js
> +              i.toString()}
"Enter a word (optional)"

2021-03-14 14:04 UTC, shu8 commented on components/CirclesAccordion/CirclesAccordion.js
> +        <text aria-label="quickSummary" id="summary">
"Quick Summary" (or can we move this `id` to the `Panel` and then remove the `<text>` element entirely so it's just the bare text?)

2021-03-14 14:05 UTC, mateuszz7 commented on components/CirclesAccordion/CirclesAccordion.js
> +        <text aria-label="quickSummary" id="summary">
i need that id injected for a test to i need that text tag

2021-03-14 16:51 UTC, shu8 approved these changes
Looks great!

2021-03-14 16:52 UTC, merged